version: "3.7"

services:
  k-client:
    container_name: k-client
    image: moisale/k-client-vue3:latest
    ports:
      - 80:80
    environment:
      - VUE_APP_API_SERVER_SCHEME=http
      - VUE_APP_API_SERVER_HOST=k-server
      - VUE_APP_API_SERVER_PORT=8090
  k-server:
    container_name: k-server
    image: moisale/k-server:latest
    ports:
      - 8090:8090
    volumes:
      - ./server/data:/app/data
    